Additional state information for data source/point
infiniteautomation/ma-modules-public pull request #189
Opened 2021-06-04 15:09 UTC by MertCingoz

2021-06-07 20:18 UTC, terrypacker commented
@MertCingoz is there a reason you check for an RTException in the model's method: `public ILifecycleState getDataPointLifecycleState()`?  

@jazdw I'm wondering if we should standardize this with the `RuntimeManager.getDataSource()` method in that it throws an exception.  But that might be a bigger deal to fix...

2021-06-07 20:28 UTC, terrypacker requested changes
See comment on "Conversation" page.

2021-06-08 11:52 UTC, MertCingoz commented
> @MertCingoz is there a reason you check for an RTException in the model's method: `public ILifecycleState getDataPointLifecycleState()`?
> 
It was left accidentally, We don't have RTException for this method

2021-06-08 14:38 UTC, jazdw approved these changes

2021-06-08 14:40 UTC, merged